version: '3.8'

services:
  mcp-weather-server:
    build: .
    ports:
      - "8124:8124"
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY:-demo}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8124/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - ./logs:/app/logs
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge